### PR TITLE
made dbNSFP fields modifiable, added dbNSFP for hg38

### PR DESCRIPTION
**Pull request by matthdsm**
fixes botched commit history from #1659

### CODE REVIEW

**Comment by matthdsm** [comment]
Thanks for the git magic pointer, otherwise it could've been a mess again!

**Comment by chapmanb** [comment]
Perfect, thanks again for the work on this.

**Comment by matthdsm** [comment]
Huraah! On to the next!

**Comment by matthdsm** [comment]
Hi Brad, 

I just realized something. The modifications I made to make dbNSFP configurable only work if the're made before the installation..
So this will require some more I think. We should be able to have a configuration file somewhere post install, where users can modify the fields used.

M

**Comment by chapmanb** [comment]
Matthias -- that's true, local changes would get over-written with new versions of the bcbio configuration files. We could migrate this to take the options from `bcbio_system.yaml` instead under a `resources` section:
```
resources:
  vep:
     dbnsfp_fields: your,custom,fields
```
and then bcbio would use the default otherwise. What do you think about that approach?

**Comment by matthdsm** [comment]
Hi Brad, 

Looks very good to me! This also gives the users the option to modify the params for each run, so I wholly support this!

M

**Pull request merged**
