### PR TITLE
Pull from DockerHub instead of importing the image

### PR DESCRIPTION
**Pull request by brainstorm**
This PR is to test whether travis passes without the conda packages and eliminates the need for a specific amazon S3 image.

### CODE REVIEW

**Comment by brainstorm** [comment]
@chapmanb, seems like pip-installing the repos directly from github would be a hassle because there's fortran code to compile in there:

https://travis-ci.org/brainstorm/bcbio-nextgen/builds/89748915

So I guess we'll have to do those changes and push a new conda release for `bcbio` and `bcbio-vm`?:

The thin PR should be safe to merge: https://github.com/chapmanb/bcbio-nextgen-vm/pull/134

@guillermo-carrasco

**Comment by brainstorm** [comment]
I was now looking into rebuilding the `bcbio` and `bcbio-vm` conda packages, but I cannot find them on the bioconda channel: https://github.com/chapmanb/bioconda-recipes

But I can find them over here:

https://conda.anaconda.org/bcbio

Can you shoot me some pointer(s) on how to rebuild those two? Thanks!

**Comment by chapmanb** [comment]
Roman -- sorry for the delay in merging and updating the conda repositories. These are not yet migrated over to bioconda. We're working on doing that slowly but have a lot of dependencies in bcbio-conda and homebrew that need migration work. It should now be up to date with your fixes to pull from Docker hub. Hope this works for you.

**Comment by brainstorm** [comment]
It worked, all green with the image from dockerhub:

https://travis-ci.org/brainstorm/bcbio-nextgen/builds/89979269

Thanks @chapmanb!

**Pull request closed without merging**
