### PR TITLE
GEMINI supports only human genome build hg19/GRCh37 for now.

### PR DESCRIPTION
**Pull request by cbrueffer**
GEMINI only supports hg19/GRCh37 for now, don't try to build DBs for other assemblies.

### CODE REVIEW

**Comment by chapmanb** [comment]
Christian -- thanks for this. We're working on incorporating the new GEMINI approach that enables hg38 (and other species) support but great to have this check in place now. Thanks again.

**Comment by cbrueffer** [comment]
Indeed, very much looking forward to that! Is there a work in progress branch somewhere yet? I'm currently looking into adding support for variant annotation with Annovar (since that's what we currently use internally), but I'd love to switch to GEMINI as soon as possible.

**Comment by ohofmann** [comment]
No branch, but working with @roryk to make sure that Gemini "2.0" works as a drop-in replacement, then migrating annotation to vcfannot using the existing annotation sources before finally testing support for hg38.

**Comment by cbrueffer** [comment]
Sounds sensible! Looks like I should have a closer look at vcfanno instead of trying to shoe-horn Annovar in.

**Pull request merged**
