### PR TITLE
added expand flag to vcf2db command

### PR DESCRIPTION
**Pull request by matthdsm**
as discussed in #1573, added `--expand` flags to vcf2db command

M

### CODE REVIEW

**Comment by chapmanb** [comment]
Matthias;
Thanks for this. We'll probably need to make expanding these columns a configuration option since it impacts the speed and size of the output database.

The best approach might be to have an `tools_on` option for this (http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#tweaking-defaults) so you can do:
```
tools_on: [vcfanno_expand]
```
that will add these options. What do you think?

**Comment by matthdsm** [comment]
Hi Brad, 

Sound great to me, although I'd call the option 'expand_genotypes', to make it sound more generic. On that same note, I probably like to see the 'gemini' param changed to 'variant_db' or something, since strictly we aren't handling gemini db's anymore. 

Thanks!
M

**Comment by chapmanb** [comment]
Mathias -- I prefer the more specific naming since the general ones can be misinterpreted. For example, if you just see `tools_on: [expand_genotypes]` it's very hard to guess what step that applies to and what is does. Similarly, `variant_db` is pretty generic and doesn't reflect that we're creating them in a certain way for querying with the GEMINI framework.

Probably `vcf2db_expand` is the right flag since that's actually the step this happens at, but happy to discuss more if you or others feel strongly about more generic names.

**Comment by matthdsm** [comment]
Hi Brad, 

Frankly, the naming doensn't matter all that much to me. I mostly care about the functionality :) However, you're right the users should be able to know which step is affected by each parameter.
I'll look into adding the option `vcf2db_expand` in the next commit. After that, I suppose this can be merged.

Thanks for the comments!
M

**Comment by matthdsm** [comment]
There we go, fixed and tested! If there aren't any new issues, I believe this can be merged.

M

**Comment by chapmanb** [comment]
Matthias -- thanks so much for this.

**Pull request merged**
