### PR TITLE
[WIP] add more vep plugins

### PR DESCRIPTION
**Pull request by matthdsm**
Starting work to add GeneSplicer,MaxEntScan and dbscSNV plugins to VEP
work to be done:

 - [x] bump vep version to 86 to include all needed plugins
 - [x] bump vep version in cloudbiolinux
 - [x] add ggd recipe for dbscSNV to Cloudbiolinux
 - [x] add function to call dbscSNV plugin
 - [x] review genesplicer recipe in Bioconda
 - [ ] ~~add genesplicer training sets to data repo for download~~
 - [x] add ggd recipe for genesplicer training sets to Cloudbiolinux
 - [x] add function to call genesplicer plugin
 - [x] add MaxEntScan recipe in Bioconda
 - [x] add function to call MaxEntScan plugin
 - [x] add option to select which plugins vep uses
 - [ ] check for compatibility with GRCh37/hg19/hg38

I've also added some comments in the code where I could use some help to further this effort.

### CODE REVIEW

**Comment by matthdsm** [comment]
cloudbiolinux related work in chapmanb/cloudbiolinux#234

**Comment by matthdsm** [comment]
Hi @chapmanb 

Just a quick question,
Is there a reason you use the `--fields` argument in VEP? I don't really see any benefits from it.

Thanks
M

**Comment by matthdsm** [comment]
Bioconda PR's
bioconda/bioconda-recipes#3123
bioconda/bioconda-recipes#3089

**Comment by matthdsm** [comment]
Hi @chapmanb,

I think the work for this is almost finished. All that's left is a function call to get the absolute path of an executable, could you help me with that?

I was also wondering if you could proofread the changes I made and see if everything is up to standard.

Thanks!
M

**Comment by chapmanb** [comment]
Matthias;
Thanks for all this brilliant work. Things are looking great and happy to merge this when ready in preparation for a 1.0.1 release with the new VEP. This will get you the shared directory where genesplicer is located for getting files:
```
genesplicer_dir = os.path.dirname(os.path.realpath(config_utils.get_program("genesplicer", data["config"])))
```
You use config_utils to get the path inside anaconda, then realpath to resolve the symlinks.

My only other suggestion is to refactor all of the "plugins" support to be less hard coded with ifs. I'd add a dictionary mapping plugins to the functions you call and build up two general arguments `plugin_args` and `plugin_fields` based on if each plugin is enabled and available.  I can handle that post-merge to be a bit cleaner as well so no big deal there. 

To answer your earlier question: the purpose of the fields argument is to ensure a consistent set of outputs in the VEP annotations.

Thanks again for all this work.

**Comment by matthdsm** [comment]
Hi Brad, 

Thanks for going through it all, I really hope I didn't mess anything up. I just pushed another commit that adds the installation path of the plugins, per your suggestion.

Do I understand correctly that you will handle the hardcoded if statements post merge? I agree the hard coded if's aren't really a nice way to check for active plugins, but I didn't really know how to handle it otherwise.

Glad to be of service!
M

**Comment by chapmanb** [comment]
Matthias;
Definitely, I'm happy to do the cleanup. I'm also working on generalizing transcript support to fix some other current issues so can do this as part of this. Thank you again for this contribution and all the hard work putting this together.

**Comment by chapmanb** [comment]
Matthias -- I checked in updates and cleanups for this so hopefully all will work as expected for your pipeline. I'm hoping to release a new bcbio version early next week with this included, so would appreciate any testing you can do before then. Thanks again.

**Comment by matthdsm** [comment]
Hi Brad, 

Thanks for merging! I'll run some tests today and get back to you with the results.
M

**Pull request merged**
