### PR TITLE
fixes for vcfanno/vcf2db error messages

### PR DESCRIPTION
**Pull request by matthdsm**
fix by @brentp https://github.com/brentp/vcfanno/commit/5fcce8db2aeee016ab927c8ca36a715c02f982f9

fixes a whole bunch of error messages from vcfanno.

### CODE REVIEW

**Comment by matthdsm** [comment]
PS, I have a cloudbiolinux PR ready for this too, so as soon as this is merged I can submit that one too.

M

**Comment by chapmanb** [comment]
Matthias -- thanks much for the fix. Much appreciated. Happy to also merge the CloudBioLinux PR when it's ready.

**Comment by matthdsm** [comment]
Hi Brad,

thanks for merging, the only remaining vcfanno errors are these
```
[2017-05-22T09:20Z] =============================================
[2017-05-22T09:20Z] vcfanno version 0.2.6 [built with go1.8]
[2017-05-22T09:20Z] see: https://github.com/brentp/vcfanno
[2017-05-22T09:20Z] =============================================
[2017-05-22T09:20Z] vcfanno.go:115: found 134 sources from 8 files
[2017-05-22T09:20Z] vcfanno.go:187: Info Error: max_aaf_all not found in INFO >> this error/warning may occur many times. reporting once here...
[2017-05-22T09:20Z] vcfanno.go:187: Info Error: clinvar_sig not found in INFO >> this error/warning may occur many times. reporting once here...
[2017-05-22T09:20Z] vcfanno.go:187: strconv.ParseFloat: parsing "c": invalid syntax >> this error/warning may occur many times. reporting once here...
[2017-05-22T09:20Z] vcfanno.go:187: strconv.ParseFloat: parsing "n": invalid syntax >> this error/warning may occur many times. reporting once here...
[2017-05-22T09:20Z] vcfanno.go:187: strconv.ParseFloat: parsing ".": invalid syntax >> this error/warning may occur many times. reporting once here...
[2017-05-22T09:20Z] vcfanno.go:187: Info Error: af_esp_all not found in INFO >> this error/warning may occur many times. reporting once here...
[2017-05-22T09:20Z] vcfanno.go:187: Info Error: af_adj_exac_sas not found in INFO >> this error/warning may occur many times. reporting once here...
```
I'm not entirely sure where they come from, especially the  `"c"`,`"n"` and `"."` errors.
Perhaps @brentp knows?

M

**Comment by brentp** [comment]
That means that one of your INFO fields that has type=Float in the header has "c" as the value somewhere in the file, and later "n".

**Pull request merged**
