### PR TITLE
When running TopHat, use TopHat-Recondition to fix the unmapped.bam file.

### PR DESCRIPTION
**Pull request by cbrueffer**
Currently the "missing 0x8 bit" problem that unmapped.bam files have
is fixed using a home-grown solution.  Instead, use TopHat-Recondition,
which fixes this problem as well as two additional problem classes.

The issues are described in detail here:
Homepage:  https://github.com/cbrueffer/tophat-recondition
Publication   http://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-1058-x

Since this requires an external program, how to ensure it is installed (it is available through bioconda)? Is cloudbiolinux contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml the right place?

### CODE REVIEW

**Comment by roryk** [comment]
Hi Christian,

Thanks for the pull request, I'm not against calling out to another tool that does the job better. The tool would need to get installed via bioconda, I can help you make a recipe for that if one doesn't exist already. We'll also need to find the `tophat-recondition` program by looking it up, like             `tophat_recondition = config_utils.get_program("tophat-recondition", data)`, since it might exist in a couple different places.

**Comment by cbrueffer** [comment]
Hi Rory,

a bioconda recipe already exists. Would ```contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml ``` in ```cloudbiolinux``` be the right place to add it? I'll test the lookup line you suggested tomorrow and update the pull request. Thanks!

**Comment by roryk** [comment]
Hi Christian,

Yup, that's the place. Thanks!

**Comment by cbrueffer** [comment]
Updated per suggestion by @roryk

**Comment by roryk** [comment]
Thanks Christian, this seems to work ok for me. The Tophat folks are also pointing people to use hisat2 instead of Tophat going forward, do you have much experience comparing the two? We've been delaying a little bit while hisat2 worked out some of its issues but things are looking more stable as of late.

**Comment by cbrueffer** [comment]
Thanks for the merge! I just started looking at hisat2 (hence the recent index fixes), can't really give an opinion yet; we've used TopHat up until now.

**Pull request merged**
