### PR TITLE
ensembl 91: updated genome resources

### PR DESCRIPTION
**Pull request by matthdsm**
Small update for the new ensembl release
Merge pending conda recipe update, there's no github release of VEP yet.

I'll update when the conda recipe is available

Cheers
M

### CODE REVIEW

**Comment by chapmanb** [comment]
Matthias -- thanks for keeping on top of this. For the YAML resources, you also need to increase the version number at the top of the file so bcbio knows to replace current versions on existing installs. Thanks again.

**Comment by matthdsm** [comment]
Hi Brad,

I already had a feeling is was forgetting something. Fixed in the latest commit.

Cheers
M

**Comment by matthdsm** [comment]
For reference: https://github.com/bioconda/bioconda-recipes/pull/7131

**Comment by matthdsm** [comment]
VEP 91 is now available in bioconda, so suppose it's safe to merge both PR's

Cheers
M

**Comment by chapmanb** [comment]
Matthias -- thank you again for all this work. Much appreciated.

**Pull request merged**
