### PR TITLE
fix for esp maf calculation

### PR DESCRIPTION
**Pull request by matthdsm**
Hi Brad,

We noticed that the function to calculate the ESP maf outputs some faulty results. I pushed a little fix for the function, and modified the name of the function to be more explanatory.

Let me know if you have any comments.

Cheers
M

### CODE REVIEW

**Comment by matthdsm** [comment]
ping @tomiles
ping @brentp, since you have the same config in the vcfanno repo

**Comment by brentp** [comment]
unless I misunderstand,
for gemini, we want to know if the alternate is rare. if it were in 99.9% of individuals, this would give it a maf of 0.001 which would make it appear rare when it is common.

**Comment by tomiles** [comment]
This request handles 2 issues:

- the definition of maf = the freq of the second most common allele, irrespective if that is the reference. This makes the results of the new function equivalent to how ESP itself calculates the freq in the MAF field of its vcf. (alternatively we could just parse the MAF field instead of calculating it ourselves)

- the ratio formula was not calculated correctly because the order of ref and alt counts was the reverse of what the VCF header specified it is.

**Comment by chapmanb** [comment]
Matthias -- I'm also confused at the intent of this, could you explain in more detail? In general we want a stable representation of alt frequency in a population so I'm not sure why we would swap ref/alts for this calculation.

**Comment by brentp** [comment]
the ESP header I'm looking at says:
```
##INFO=<ID=EA_AC,Number=R,Type=String,Description="European American Allele Count in the order of RefAllele,AltAlleles. For INDELs, A1, A2, or An refers to the N-th alternate allele while R refers to the reference allele.">
```
so the first allele is always the ref. To get alternate alelle count, we would then do `v[2] / (v[1] + v[2])`, yes? 

if you want minor allele frequency, your change is correct, but in gemini, we want alternate allele frequency.

**Comment by matthdsm** [comment]
That's weird....
The ESP file I have here contains this header:
```
##INFO=<ID=EA_AC,Number=.,Type=String,Description="European American Allele Count in the order of AltAlleles,RefAllele. For INDELs, A1, A2, or An refers to the N-th alternate allele while R refers to the reference allele.">
```

I'm using the ESP vcf file that was installed by the bcbio installer. It seems like there's some kind of mixup between files then..

M

**Comment by tomiles** [comment]
The vcf from the http://evs.gs.washington.edu/EVS/ download section has the header with the order of AltAlleles,RefAllele
=> http://evs.gs.washington.edu/evs_bulk_data/ESP6500SI-V2-SSA137.GRCh38-liftover.snps_indels.vcf.tar.gz

**Comment by brentp** [comment]
oh, I see. we're still using the old 37 version. We should verify with the UW folks that what's in the header is correct as that is suprising. 
@jxchong, do you know about this?

**Comment by matthdsm** [comment]
I just opened a new PR, where I've switched the values in the calculation. Everything should be correct now.

Cheers
M

**Pull request closed without merging**
