### PR TITLE
made dbNSFP fields modifiable, added dbNSFP for hg38

### PR DESCRIPTION
**Pull request by matthdsm**
Hi Brad

I've tried to make some modifications to how dbNSFP was called with VEP. As I said in #1653 , It'd be nice I the users could modify which fields are used.

This PR aims to do just that. However, I haven't been able to test this (how should I go about that?).
Do you think this seems allright?

this goes together with chapmanb/cloudbiolinux#233

Thanks
M

### CODE REVIEW

**Comment by chapmanb** [comment]
Thanks for this. The approach looks great to me. Could you make the default dbNSFP annotations the same as previously so that folks upgrading get the previous behavior? It's great to allow people to adjust but would like to make the experience consistent for anyone who is currently reliant on the existing behavior. Thanks again.

**Comment by matthdsm** [comment]
Done!
Do you suppose this will work out of the box? I don't really have an idea how I should best test this before doing a PR.

**Comment by matthdsm** [comment]
I tried adding the dbscSNV plugin in the latest commit, I thinks that should do the trick, but I might have forgotten to make some other changes somewhere. This does depend on the upgrade to vep_86, since the plugin file isn't included in the vep_83 recipe.

**Comment by chapmanb** [comment]
Thanks for working more on this. I'm happy to merge the dbNSFP changes if you can separate out your branches again. No problem to close and re-open or whatever works best for you. For testing, you can install your development version of the code into your current installation (or a second development installation) and the details about how we typically are here:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/code.html#development-infrastructure

Hope this helps.

**Comment by matthdsm** [comment]
Ok, I think I reverted everything that doesn't belong here. If you don't see any more issues, merge away!

**Comment by chapmanb** [comment]
Thanks, this looks great to me but I'm not able to cleanup the messy history of this because of the merges. Would it be possible to create a new clean branch submit a PR from that? You could do without any git magic with:
```
git checkout -b vep-dbnsfp
wget https://patch-diff.githubusercontent.com/raw/chapmanb/bcbio-nextgen/pull/1659.diff
patch -p1 < 1659.diff
```
and then submit from that new branch. I could do but wanted to give you credit for your work in the git history. I'll close this for now and can merge your new PR whenever ready.

**Pull request closed without merging**
