### PR TITLE
updated vep cache version

### PR DESCRIPTION
**Pull request by matthdsm**
To be merged after issues with recipe for v87 are resolved
bioconda/bioconda-recipes#3177

### CODE REVIEW

**Comment by chapmanb** [comment]
Thanks for this, happy to put this in place once the VEP issues get resolved in bioconda. For this patch, can you also increase the version numbers for each of the changed resource files? That ensures the new configuration gets pulled into place during a bcbio update. Thanks again.

**Comment by matthdsm** [comment]
Done!

**Comment by matthdsm** [comment]
Recipe is merged, so I think this can be merged too.

M

**Comment by chapmanb** [comment]
Matthias -- thanks again for getting this all updated.

**Pull request merged**
