### PR TITLE
Ensembl vep update

### PR DESCRIPTION
**Pull request by matthdsm**
TODO:
- [x] Update vep script calls for new version
- [x] Remove dbNSFP and dbscSNV plugin functions from effects.py
- [x] (optional) Update dbNSFP and other refs (chapmanb/cloudbiolinux#246)
- [x] add vcfanno config files for dbscSNV and dbNSFP
- [x] update genome resource files to use the latest ensembl release
- [x] update vep conda requirement in cloudbiolinux
- [ ] ...

Brad, if you have any more todo's please add then to the list.

Cheers
M

### CODE REVIEW

**Comment by matthdsm** [comment]
I'm fairly sure the vcfanno configs are correct, but perhaps the `ops` section might benefit from a second opinion.
Both files should be usable out of the box by specifying  `vcfanno: [gemini, dbsnfp, dbscsnv` in the config file.

**Comment by matthdsm** [comment]
Hi Brad,

Could you re-trigger the last travis build for the last commit? something seems to have gone wrong there.

Thanks!
M

**Comment by chapmanb** [comment]
Matthias;
Sorry about the issue, this is an unrelated problem due to changes in our CWL pipeline that are currently on going. If you want to avoid the error you can rebase against the current master (`git pull --rebase upstream master`) to disable this test. Hope this gets it cleanly running through the tests for you.

**Comment by matthdsm** [comment]
Hi Brad, 

Are you still interested in this? Too bad the changes didn't make it into the latest release, but I'm hoping for the next.

Cheers
M

**Comment by chapmanb** [comment]
Matthias;
Thanks for following up. I definitely want to include this and was aiming for a post 1.0.3 release since I didn't want another round of testing before that release. If it's good to go now I can merge and we can start testing now. Thanks for the patience.

**Comment by matthdsm** [comment]
Hi Brad,

Thanks for replying. I've ran some tests locally, and haven't found any issues yet, so I think we're good to go here. I'll open another PR later this month if the new ensembl release is out. v89 will include a new version of COSMIC and GnomAD, so I think it might be worthwhile.

Cheers!
M

**Comment by chapmanb** [comment]
Matthias;
Sounds great. I was reviewing and realized the PR has gotten a little mixed up with a bunch of non-related changes from the master branch incorporated. Would you be able to prepare a clean PR with only the `bcbio/variation/effects.py` and `config` changes? If it's a pain let me know and I can try to incorporate but would like to give you direct credit for all your work in the git history. Thanks again.

**Comment by matthdsm** [comment]
Hi Brad,

No problem, you can expect a new PR shortly.

Cheers
M

**Pull request closed without merging**
