### PR TITLE
iRODS download

### PR DESCRIPTION
**Pull request by matthdsm**
Hi @chapmanb,

I pushed my initial work towards iRODS download functionality. I was wondering if you could check it out and see if I haven't forgotten anything and/or going the completely wrong way with this.

Thanks!
M

### CODE REVIEW

**Comment by chapmanb** [comment]
Matthias -- is this ready to merge or did you want to do more work/testing on it? The general implementation looks great to me.  I don't have a way to test but it shouldn't be disruptive to any other uses so happy to get it in and have folks start using it if you're happy with the current state. Thanks again.

**Comment by matthdsm** [comment]
Hi Brad, 

Thanks for looking into it. I've been a bit pressed on time since this PR, so I haven't been able to any tests, and I was waiting for initial approval of the code. I'll let you know if this is ready for prime time (read, if got around to testing it thoroughly).

Thanks again
M

**Comment by matthdsm** [comment]
Hi Brad, 

just a quick related question. Do you have timeframe you are looking at for a new release? If possible I'd like to have everything tested and running before that. That way when we update our production instance, everything's there.

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
We don't have a firm date but normally try to have releases every month to two months so will likely start putting it together in the next couple of weeks. Hope this helps.

**Pull request closed without merging**
