### PR TITLE
Fixes for VEP

### PR DESCRIPTION
**Pull request by matthdsm**
Hi Brad,

This PR goes with #1766 and should fix most of the issues.
I haven't put any work towards the `--fields` argument, seeing as I'd like to remove it completely and I don't really know your position on this.

I'll run some tests locally to make sure everything works like it should.
M

### CODE REVIEW

**Comment by matthdsm** [comment]
Hi @chapmanb, 

I think this should be it as far as fixing VEP goes. 
The only remaining issues here are
- GeneSplicer still isn't included, although I hope this will be fixed be removing the trailing slashes
- The use of the `--fields ` argument hasn't been dropped, even though I think it should.

I also noticed the `dbNSFP` annotations don't seem to work anymore. The header and CSQ tag have all the info, but no variants were annotated (tested on a giab sample).

**Comment by chapmanb** [comment]
Matthias -- thanks for all these improvements, happy to get these in. Have you been able to test the changes to the GeneSplicer directory to see if they work? Likewise, any insight into the dbNSFP annotation failure? It seems worth resolving these before making any other adjustments to the module. We typically use a SnpEff/GEMINI based annotation framework so I don't have a ton of experience here, so leaning on what is working in your workflows. Thanks again for testing and helping on this.

**Comment by matthdsm** [comment]
Hi Brad, 
Unfortunatly, I haven't been able to test the modifications to Genesplicer (unless you can tell me where I can find the genome_resource config files post installation?) As for dbNSFP, this has always quite the annoying plugins, since it seems to be a bit hit and miss at times. I'll try rebuilding the dbNSFP file first and test it again.
Alternatively, perhaps we can collaborate with @brentp so vcfanno can handle the dbNSFP file, or even better, dbNSFP without the preprocessing.

M

**Comment by matthdsm** [comment]
Hi Brad, 

your comment in my other PR gave me an idea. How about we put the extra plugins for vep under tools_on?
something like:
``` 
tools_on:
  - vcf2db_expand
  - vep_extras: [genesplicer, maxentscan]
```
although I'm not really sure `tools_on` supports nested options. What do you think? It fits the model of "tweaking defaults".

Thanks
M

**Comment by chapmanb** [comment]
Matthias -- thanks for the continued work on this. Are there cases where you only want specifically one of genesplicer or maxentscan? If we could get away with a single `tools_on: vep_splicesite_annotations` that would help reduce the number of parameters. Sorry for the pushback but trying to fight back too many configuration parameters is one of the hardest things to do. Thanks again.

**Comment by matthdsm** [comment]
Hi Brad, 

No problem, I'll merge the two options! If you find the time, could you have a look at the genesplicer issue? I've tried identifying the problem, but to avail. the resource doesn't get included into the config dict.

thanks!
M

**Comment by matthdsm** [comment]
New PR with clean history #1784

**Pull request closed without merging**
