### PR TITLE
Fixes for VEP

### PR DESCRIPTION
**Pull request by matthdsm**
same as #1771, but without the screwed up history.

Should be safe to merge, if no problems arise.

Thanks!
M

### CODE REVIEW

**Comment by matthdsm** [comment]
Hi Brad, 

Could you trigger a new travis check for this? There doesn't seem to be anything wrong, and I think this can be merged.

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
Absolutely, apologies for the delay. I'd had this one on hold as I thought you were still investigating the genesplicer issue. As far as I can tell the specification looks okay to me, and I bumped the versions of the genome resources files to ensure the new ones get pulled into installation. Hope this gets VEP working cleanly for you.

**Comment by matthdsm** [comment]
Hi Brad, 

Thanks for merging. To be 100% fair, I didn't find the genesplicer issue. As I said in the previous PR, it seems like the genesplicer resource doesn't get added to the big `config` dict, and I'be got no idea where to look to fix it. I was hoping you could point me in the right direction for that.
Thanks again
M

**Comment by chapmanb** [comment]
Matthias;
Genesplicer seemed to be added normally in my tests on smaller datasets so I'm not sure what is wrong right now. Did you definitely have the updated `*-resources.yaml` files with genesplicer in them in your configuration? I'm hoping that might explain the problem.

**Comment by matthdsm** [comment]
I updated everything I could find during my tests. I just updated to the latest dev version and will do some more testing. I'll let you know if the problem still occurs!
Thanks
M

**Pull request merged**
